language: python

python:
  - "2.7"

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo" EXCLUDE="sale_order_types,stock_invoicing_type"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" EXCLUDE="sale_order_types,stock_invoicing_type"

virtualenv:
  system_site_packages: true

install:
  - sudo pip install unidecode
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/pedrobaeza/banking ${HOME}/banking -b 8.0-sepa-migration
  - git clone https://github.com/OCA/purchase-workflow ${HOME}/purchase-workflow -b ${VERSION}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}

script:
  - travis_run_tests ${VERSION}

after_success:
  coveralls
